config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/about'

  get 'quizzes/new'

  get 'games/new'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/home',   to: 'static_pages#home'
  get  '/scoreboard', to: 'static_pages#leaderboard'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'play(/:id)', to: 'games#play', as: :play
  post 'state_update/', to: 'games#state_update', as: :state_update
  get 'show_leaderboard/:id/:row_id', to: 'games#show_leaderboard', as: :leaderboard
  get 'quizzes/show/:id/', to: 'quizzes#show_all_quizzes', as: :show_all_quizzes
  get 'subcategories/show/:id', to: 'subcategories#show_all_subcategories', as: :show_all_subcategories
  get 'users/show_past_history', to: 'users#show_past_history', as: :show_past_history
  get 'games/show_correct', to: 'games#show_correct', as: :show_correct
  get 'auth/:provider/callback', to: 'sessions#extauth'
  get 'auth/google_oauth2', as: :auth_google
  get 'auth/failure', to: 'static_pages#home'
  post 'play/show_correct_options', to: 'games#show_two_options', as: :show_two_options
  post 'play/audience_poll', to: 'games#audience_poll', as: :audience_poll
  resources :users
  resources :complaints
  resources :logs
  resources :questions,     only: [:create, :new, :index, :destroy, :edit, :update]
  resources :categories,    only: [:create, :new, :index, :destroy, :edit, :update]
  resources :subcategories, only: [:create, :new, :index, :destroy, :edit, :update]
  resources :questions,     only: [:create, :new, :index, :destroy, :edit, :update]
  resources :quizzes,       only: [:create, :new, :index, :destroy, :edit, :update]
end

app/models/assign.rb
class Assign < ApplicationRecord
  belongs_to :complaint
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many  :subcategories, dependent: :destroy
  has_many  :scores, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 100 },
            uniqueness: { case_sensitive: false }
end

app/models/complaint.rb
class Complaint < ApplicationRecord
end

app/models/lifeline.rb
class Lifeline < ApplicationRecord
  belongs_to :quiz
  belongs_to :user
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :complaint
  belongs_to :user
end

app/models/q_image.rb
class QImage < ApplicationRecord
  belongs_to :question
end

app/models/q_state.rb
class QState < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many :q_states, dependent: :destroy
  has_many :q_images, dependent: :destroy
  validates :name,  presence: true
  validates :qtype,  presence: true
  validates :content,  presence: true
  validates :option_one,  presence: true
  validates :option_two,  presence: true
  validates :option_three,  presence: true
  validates :option_four,  presence: true
  validates :answer,  presence: true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many  :questions, dependent: :destroy
  has_many  :scores, dependent: :destroy
  has_many  :q_states, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 100 },
             uniqueness: { case_sensitive: false }
  belongs_to :subcategory
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  #belongs_to :quiz
  #belongs_to :subcategory
  #belongs_to :category
  validates :total,  presence: true
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :user
  belongs_to :quiz
  validates :count,  presence: true
  validates :score,  presence: true
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  has_many :quizzes, dependent: :destroy
  has_many :scores, dependent: :destroy
  validates :category_id, presence: true
  validates :name,  presence: true, length: { maximum: 100 },
            uniqueness: { case_sensitive: false }
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  require 'securerandom'

  has_many  :scores, dependent: :destroy
  has_many  :states, dependent: :destroy
  has_many  :q_states, dependent: :destroy
  has_many  :lifelines, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.password = SecureRandom.urlsafe_base64(10)
      user.email = auth.info.email
      user.gender = auth.info.gender
      user.save!
    end
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :logged_in_user, only: [:index, :new, :create]
  before_action :admin_user,     only: [:destroy, :new, :create, :update, :edit]

  def new
    @subcategory = Subcategory.new
    @categories = Category.all
  end

  def create
    @subcategory = Subcategory.new(subcategories_params)
    if @subcategory.save
      flash[:success] = "Congratulations. You have created a new subcategory!!"
      redirect_to subcategories_url
    else
      render 'new'
    end
  end

  def index
    @subcategories = Subcategory.all
  end

  def edit
    @subcategory = Subcategory.find(params[:id])
    @categories = Category.all
  end

  def update
    @subcategory = Subcategory.find(params[:id])
    if @subcategory.update_attributes(subcategories_params)
      flash[:success] = "Subcategory updated successfully"
      redirect_to subcategories_path
    else
      render 'edit'
    end
  end

  def destroy
    Subcategory.find(params[:id]).destroy
    flash[:success] = "Category deleted"
    redirect_to categories_url
  end

  def show_all_subcategories
    category_id = params[:id]
    @subcategories = Subcategory.where(category_id: category_id)
  end

  private
    def subcategories_params
      params.require(:subcategory).permit(:name, :category_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://www.gravatar.com/avatar/#{gravatar_id}.png?d=monsterid&s=#{size}"
    image_tag(gravatar_url, alt: user.name, :class => "text-center")
  end

  def show_score(user)
    score = Score.where(user_id: user.id, is_quiz: true)
    score_sum = score.sum(:total)
    score_count = score.count
    if score_count == 0
      @rating = "Unrated"
    else
      @rating = score_sum/score_count
    end
  end

end

app/views/subcategories/edit.html.erb
<% provide(:title, 'Edit Subcategory') %>
<h1 class="text-center">Edit Subcategory</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=	 form_for @subcategory, :html => {:class => 'form-horizontal'} do |f| %>
        <%=	 render 'shared/subcategory_error_messages' %>
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        <%= f.label :category_id, class: 'control-label' %>
        <select name="subcategory[category_id]" id="subcategory_category_id" class="form-control">
          <% @categories.each do |category| %>
            <option value="<%= category.id %>">
              <%= category.name %>
            </option>
          <% end %>
        </select>
        <br>
        <%= f.submit "Edit subcategory", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/subcategories/index.html.erb
<% provide(:title, 'All Subcategories') %>
<h1 class="text-center">All Subcategories</h1>

<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>#</th>
    <th>Subcategory Name</th>
    <th>Quizzes</th>
    <th>Leader Board</th>
    <% if current_user.admin? %>
        <th>Edit</th>
        <th>Delete</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <%= ctr = 0 %>
  <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= ctr + 1 %></td>
        <td><%=	 subcategory.name %></td>
        <td><%=	 link_to "Quizzes", show_all_quizzes_path(subcategory.id) %></td>
        <td><%=	link_to "Leader Board", leaderboard_path(2, subcategory.id) %></td>
        <% if current_user.admin? %>
            <td><%= link_to "Edit", edit_subcategory_path(subcategory.id) %></td>
            <td><%=	 link_to "Delete", subcategory, method: :delete, data: { confirm: "Are you sure?" } %></td>
        <% end %>
      </tr>
      <%=	 ctr = ctr + 1 %>
  <% end %>
  </tbody>
</table>

app/views/subcategories/new.html.erb
<% provide(:title, 'Create Subcategory') %>
<h1 class="text-center">Create Subcategory</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=	 form_for @subcategory, :html => {:class => 'form-horizontal'} do |f| %>
        <%=	 render 'shared/subcategory_error_messages' %>
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        <%= f.label :category_id, class: 'control-label' %>
        <select name="subcategory[category_id]" id="subcategory_category_id" class="form-control">
          <% @categories.each do |category| %>
            <option value="<%= category.id %>">
              <%= category.name %>
            </option>
          <% end %>
        </select>
        <br>
        <%= f.submit "Create subcategory", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/subcategories/show_all_subcategories.html.erb
<% provide(:title, 'Subcategories') %>
<h1 class="text-center">Subcategories</h1>

<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>#</th>
    <th>Subcategory Name</th>
    <th>Quizzes</th>
    <% if current_user.admin? %>
        <th>Delete</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <%= ctr = 0 %>
  <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= ctr + 1 %></td>
        <td><%=	 subcategory.name %></td>
        <td><%=	 link_to "Quizzes", show_all_quizzes_path(subcategory.id) %></td>
        <% if current_user.admin? %>
            <td><%=	 link_to "Delete", subcategory, method: :delete, data: { confirm: "Are you sure?" } %></td>
        <% end %>
      </tr>
      <%=	 ctr = ctr + 1 %>
  <% end %>
  </tbody>
</table>